(()=>{
  const D=window.KFOrganizations;if(!D)return;
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let all=D.loadAll(),type='Школа',align='Особые',selectedId=null,staff=false,editingId=null,pendingImage='',pendingThumb='';
  const typeLabel={Школа:'Школы',Секта:'Секты',Фракция:'Фракции'};
  function visible(){return all.filter(x=>!x.hidden&&D.category(x.category)===type&&D.alignment(x.alignment)===align)}
  function current(){const list=visible();let x=list.find(v=>String(v.id)===String(selectedId));if(!x)x=list[0]||null;if(x)selectedId=x.id;return x}
  async function role(){let u=null;try{u=JSON.parse(localStorage.getItem('kungfuCurrentUser')||'null')}catch{};staff=!!u&&['admin','moderator'].includes(u.role||'user');if(window.KFSupabase?.ready){try{await window.KFSupabase.ready;const p=await window.KFSupabase.getCurrentProfile();if(p){staff=['admin','moderator'].includes(p.role||'user');localStorage.setItem('kungfuCurrentUser',JSON.stringify(p))}}catch{}}$('orgStaff').classList.toggle('show',staff)}
  function renderTabs(){document.querySelectorAll('.org-tab').forEach(b=>b.classList.toggle('active',b.dataset.type===type));document.querySelectorAll('.org-align').forEach(b=>b.classList.toggle('active',b.dataset.align===align))}
  function summary(v,max=230){v=String(v||'').replace(/\s+/g,' ').trim();return v.length>max?v.slice(0,max-1)+'…':v}
  function render(){renderTabs();const x=current(),list=visible(),stage=$('orgStage');if(!x){stage.innerHTML=`<div class="org-empty"><strong>${typeLabel[type]}</strong>В категории «${esc(align)}» пока нет записей.${staff?'<div style="margin-top:15px"><button class="org-btn primary" id="emptyAdd">+ Добавить</button></div>':''}</div>`;if(staff&&$('emptyAdd'))$('emptyAdd').onclick=()=>openEditor(null);$('orgThumbs').innerHTML='';return}
    const icon=x.thumbImage||x.image||'';
    stage.innerHTML=`<div class="org-grid"><div class="org-copy"><div class="org-copy-head">${icon?`<div class="org-icon-badge"><img src="${esc(icon)}" alt=""></div>`:''}<div class="org-copy-main"><span class="org-kicker">${esc(type)} · ${esc(align)}</span><h2 class="org-name">${esc(x.name)}</h2></div></div><div class="org-facts"><div class="org-fact"><b>Расположение</b><span>${esc(x.location||'Не заполнено')}</span></div><div class="org-fact"><b>Оружие</b><span>${esc(x.weapon||'Не заполнено')}</span></div></div><p class="org-summary">${esc(summary(x.content||'Описание будет добавлено позже.'))}</p>${x.features?`<div class="org-feature-note"><b>Особенности:</b> <span>${esc(x.features)}</span></div>`:''}<div class="org-actions"><a class="org-btn primary" href="school-detail.html?id=${encodeURIComponent(x.id)}">Подробнее</a>${staff?`<button class="org-btn" id="quickEdit">Редактировать карточку</button>`:''}</div></div><div class="org-image-wrap">${x.image?`<img class="org-image" src="${esc(x.image)}" alt="${esc(x.name)}">`:'<div class="org-empty">Большое изображение не добавлено</div>'}</div></div>`;
    if(staff&&$('quickEdit'))$('quickEdit').onclick=()=>openEditor(x.id);
    $('orgThumbs').innerHTML=list.map(v=>{const thumb=v.thumbImage||v.image||'';return `<button class="org-thumb ${String(v.id)===String(x.id)?'active':''}" data-id="${esc(v.id)}">${thumb?`<img src="${esc(thumb)}" alt="">`:'<div class="thumb-fallback">Нет иконки</div>'}<small>${esc(v.name)}</small></button>`}).join('');$('orgThumbs').querySelectorAll('.org-thumb').forEach(b=>b.onclick=()=>{selectedId=b.dataset.id;render()})}
  function move(dir){const list=visible();if(!list.length)return;let i=list.findIndex(x=>String(x.id)===String(selectedId));if(i<0)i=0;i=(i+dir+list.length)%list.length;selectedId=list[i].id;render();document.querySelector('.org-thumb.active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}
  function imgToData(file,max=1600){return window.KFImageTools?.process?window.KFImageTools.process(file,{maxSide:max,preserveBytes:4*1024*1024,targetBytes:3*1024*1024}):new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
  function preview(id,val){const p=$(id);if(val){p.src=val;p.classList.add('show')}else p.classList.remove('show')}
  function openEditor(id){if(!staff)return;editingId=id;const x=id?all.find(v=>String(v.id)===String(id)):null;pendingImage=x?.image||'';pendingThumb=x?.thumbImage||x?.image||'';$('edTitle').textContent=x?'Редактировать карточку':'Добавить организацию';$('edCategory').value=x?D.category(x.category):type;$('edAlign').value=x?D.alignment(x.alignment):align;$('edName').value=x?.name||'';$('edLocation').value=x?.location||'';$('edWeapon').value=x?.weapon||'';$('edFeatures').value=x?.features||'';$('edContent').value=x?.content||'';$('edJoin').value=x?.howToJoin||'';$('edImage').value='';$('edThumb').value='';preview('edPreview',pendingImage);preview('edThumbPreview',pendingThumb);$('orgModal').classList.add('open')}
  function closeEditor(){$('orgModal').classList.remove('open');editingId=null;pendingImage='';pendingThumb=''}
  async function saveEditor(){if(!staff)return;const name=$('edName').value.trim();if(!name)return alert('Укажите название');const old=editingId?all.find(v=>String(v.id)===String(editingId)):null;const row=D.normalize({...old,id:old?.id||('org-'+Date.now()),category:$('edCategory').value,alignment:$('edAlign').value,name,location:$('edLocation').value.trim()||'Не заполнено',weapon:$('edWeapon').value.trim()||'Не заполнено',features:$('edFeatures').value.trim(),content:$('edContent').value.trim()||'Описание будет добавлено позже.',howToJoin:$('edJoin').value.trim()||'Информация будет добавлена позже.',image:pendingImage,thumbImage:pendingThumb,articleHtml:old?.articleHtml||'',hidden:false,authorRole:old?.authorRole||JSON.parse(localStorage.getItem('kungfuCurrentUser')||'{}').role||'admin'});if(old)all[all.indexOf(old)]=row;else all.push(row);try{all=await D.persist(all);type=row.category;align=row.alignment;selectedId=row.id;closeEditor();render()}catch(e){alert(e.message||'Не удалось сохранить организацию')}}
  async function del(){if(!staff)return;const x=current();if(!x||!confirm(`Удалить «${x.name}»?`))return;const i=all.findIndex(v=>String(v.id)===String(x.id));if(i>=0)all[i]={...all[i],hidden:true};try{all=await D.persist(all);selectedId=null;render()}catch(e){alert(e.message||'Не удалось удалить')}}
  document.querySelectorAll('.org-tab').forEach(b=>b.onclick=()=>{type=b.dataset.type;const entries=all.filter(x=>!x.hidden&&D.category(x.category)===type);align=entries.some(x=>D.alignment(x.alignment)==='Особые')?'Особые':'Добро';selectedId=null;render()});document.querySelectorAll('.org-align').forEach(b=>b.onclick=()=>{align=b.dataset.align;selectedId=null;render()});
  $('prevOrg').onclick=()=>move(-1);$('nextOrg').onclick=()=>move(1);$('staffAdd').onclick=()=>openEditor(null);$('staffEdit').onclick=()=>{const x=current();if(x)openEditor(x.id)};$('staffDelete').onclick=del;$('edClose').onclick=closeEditor;$('edCancel').onclick=closeEditor;$('edSave').onclick=saveEditor;$('orgModal').onclick=e=>{if(e.target===$('orgModal'))closeEditor()};$('edImage').onchange=async()=>{try{pendingImage=await imgToData($('edImage').files[0]);preview('edPreview',pendingImage)}catch(e){alert(e.message)}};$('edThumb').onchange=async()=>{try{pendingThumb=await imgToData($('edThumb').files[0],900);preview('edThumbPreview',pendingThumb)}catch(e){alert(e.message)}};
  const q=new URLSearchParams(location.search);if(q.get('type'))type=D.category(q.get('type'));if(q.get('align'))align=D.alignment(q.get('align'));if(q.get('id'))selectedId=q.get('id');
  Promise.all([role(),D.hydrate().then(v=>{all=v})]).finally(()=>{render();if(q.get('edit')&&staff)setTimeout(()=>openEditor(q.get('edit')),40)});
})();
