(()=>{
  const D=window.KFOrganizations;if(!D)return;const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));let all=D.loadAll(),id=new URLSearchParams(location.search).get('id'),item=D.findById(id,all),staff=false,pendingImage='';
  function lines(v){return String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}function safe(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
  function cards(title,arr){if(!Array.isArray(arr)||!arr.length)return'';return `<section class="detail-section"><h2>${esc(title)}</h2><div class="detail-cards">${arr.map(x=>`<article>${x.image?`<img src="${esc(x.image)}" alt="">`:''}<div><h3>${esc(x.name||'')}</h3><p>${esc(x.description||'')}</p></div></article>`).join('')}</div></section>`}
  function render(){if(!item||item.hidden){$('detailApp').innerHTML='<div class="detail-empty">Материал не найден.</div>';return}document.title=`${item.name} — Легенды Кунг-Фу`;$('detailApp').innerHTML=`<div class="detail-breadcrumb"><a href="schools.html?type=${encodeURIComponent(item.category)}&align=${encodeURIComponent(item.alignment)}">Школы, секты и фракции</a><span>›</span><span>${esc(item.name)}</span></div><section class="detail-hero org-panel"><div class="detail-copy"><span class="org-kicker">${esc(item.category)} · ${esc(item.alignment)}</span><h1>${esc(item.name)}</h1><div class="detail-facts"><div><b>Локация</b><span>${esc(item.location||'Не заполнено')}</span></div><div><b>Оружия</b><span>${esc(item.weapon||'Не заполнено')}</span></div></div>${staff?'<button class="org-btn primary" id="detailEdit">Редактировать страницу</button>':''}</div><div class="detail-image">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.name)}">`:''}</div></section><section class="detail-section org-panel"><h2>Описание</h2><p>${esc(item.content||'Описание будет добавлено позже.').replace(/\n/g,'<br>')}</p></section><section class="detail-section org-panel"><h2>Как вступить?</h2><p>${esc(item.howToJoin||'Информация будет добавлена позже.').replace(/\n/g,'<br>')}</p></section>${cards('Нейгуны',item.neigongCards)}${cards('Навыки',item.skillCards)}${renderLinks(item.links)}<div class="detail-bottom"><a class="org-btn" href="schools.html?type=${encodeURIComponent(item.category)}&align=${encodeURIComponent(item.alignment)}">← Вернуться к витрине</a></div>`;if(staff&&$('detailEdit'))$('detailEdit').onclick=openEditor}
  function renderLinks(v){const a=lines(v);if(!a.length)return'';return `<section class="detail-section org-panel"><h2>Ссылки</h2><ul>${a.map(s=>{const p=s.split('|'),url=safe((p[1]||p[0]).trim()),label=(p[1]?p[0]:'Перейти').trim();return url?`<li><a href="${url}" target="_blank" rel="noopener">${esc(label)}</a></li>`:`<li>${esc(s)}</li>`}).join('')}</ul></section>`}
  async function role(){let u=null;try{u=JSON.parse(localStorage.getItem('kungfuCurrentUser')||'null')}catch{};staff=!!u&&['admin','moderator'].includes(u.role||'user');if(window.KFSupabase?.ready){try{await window.KFSupabase.ready;const p=await window.KFSupabase.getCurrentProfile();if(p)staff=['admin','moderator'].includes(p.role||'user')}catch{}}}
  function openEditor(){if(!staff||!item)return;pendingImage=item.image||'';$('dCategory').value=item.category;$('dAlign').value=item.alignment;$('dName').value=item.name;$('dLocation').value=item.location||'';$('dWeapon').value=item.weapon||'';$('dContent').value=item.content||'';$('dJoin').value=item.howToJoin||'';$('dImage').value='';const p=$('dPreview');if(pendingImage){p.src=pendingImage;p.classList.add('show')}else p.classList.remove('show');$('detailModal').classList.add('open')}
  function closeEditor(){$('detailModal').classList.remove('open')}
  function imgToData(file,max=1600){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>5*1024*1024)return reject(new Error('Файл больше 5 МБ'));const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.88))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
  function save(){if(!staff)return;const name=$('dName').value.trim();if(!name)return alert('Укажите название');const updated=D.normalize({...item,category:$('dCategory').value,alignment:$('dAlign').value,name,location:$('dLocation').value.trim()||'Не заполнено',weapon:$('dWeapon').value.trim()||'Не заполнено',content:$('dContent').value.trim()||'Описание будет добавлено позже.',howToJoin:$('dJoin').value.trim()||'Информация будет добавлена позже.',image:pendingImage});const i=all.findIndex(x=>String(x.id)===String(item.id));all[i]=updated;item=updated;D.saveAll(all);closeEditor();render()}
  $('dClose').onclick=closeEditor;$('dCancel').onclick=closeEditor;$('dSave').onclick=save;$('detailModal').onclick=e=>{if(e.target===$('detailModal'))closeEditor()};$('dImage').onchange=async()=>{try{pendingImage=await imgToData($('dImage').files[0]);$('dPreview').src=pendingImage;$('dPreview').classList.add('show')}catch(e){alert(e.message)}};role().finally(render);
})();
