(()=>{
  const D=window.KFOrganizations;if(!D)return;
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let all=D.loadAll(), type='Школа', align='Особые', selectedId=null, staff=false, editingId=null, pendingImage='';
  const typeLabel={Школа:'Школы',Секта:'Секты',Фракция:'Фракции'};
  function visible(){return all.filter(x=>!x.hidden&&D.category(x.category)===type&&D.alignment(x.alignment)===align)}
  function current(){const list=visible();let x=list.find(v=>String(v.id)===String(selectedId));if(!x)x=list[0]||null;if(x)selectedId=x.id;return x}
  function excerpt(v){const s=String(v||'').replace(/\s+/g,' ').trim();if(!s||s==='Описание будет добавлено позже.')return'';return s.length>260?s.slice(0,257)+'…':s}
  async function role(){let u=null;try{u=JSON.parse(localStorage.getItem('kungfuCurrentUser')||'null')}catch{};staff=!!u&&['admin','moderator'].includes(u.role||'user');if(window.KFSupabase?.ready){try{await window.KFSupabase.ready;const p=await window.KFSupabase.getCurrentProfile();if(p){staff=['admin','moderator'].includes(p.role||'user');localStorage.setItem('kungfuCurrentUser',JSON.stringify(p))}}catch{}}$('orgStaff').classList.toggle('show',staff)}
  function renderTabs(){document.querySelectorAll('.org-tab').forEach(b=>b.classList.toggle('active',b.dataset.type===type));document.querySelectorAll('.org-align').forEach(b=>b.classList.toggle('active',b.dataset.align===align))}
  function render(){renderTabs();const x=current(), list=visible(),stage=$('orgStage');
    if(!x){stage.innerHTML=`<div class="org-empty"><strong>${typeLabel[type]}</strong>В категории «${esc(align)}» пока нет записей.${staff?'<div style="margin-top:15px"><button class="org-btn primary" id="emptyAdd">+ Добавить</button></div>':''}</div>`;if(staff&&$('emptyAdd'))$('emptyAdd').onclick=()=>openEditor(null);$('orgThumbs').innerHTML='';return}
    const text=excerpt(x.content);
    stage.innerHTML=`<div class="org-grid"><div class="org-copy"><span class="org-kicker">${esc(type)} · ${esc(align)}</span><h2 class="org-name">${esc(x.name)}</h2><div class="org-facts"><div class="org-fact"><b><span class="org-fact-icon">●</span>Локация</b><span>${esc(x.location||'Не заполнено')}</span></div><div class="org-fact"><b><span class="org-fact-icon">⚔</span>Оружия</b><span>${esc(x.weapon||'Не заполнено')}</span></div></div>${text?`<p class="org-summary">${esc(text)}</p>`:''}<div class="org-actions"><a class="org-btn primary" href="school-detail.html?id=${encodeURIComponent(x.id)}">Подробнее ›</a>${staff?`<button class="org-btn" id="quickEdit">Редактировать</button>`:''}</div></div><div class="org-image-wrap">${x.image?`<img class="org-image-ghost" src="${esc(x.image)}" alt="" aria-hidden="true"><img class="org-image" src="${esc(x.image)}" alt="${esc(x.name)}" loading="eager">`:'<div class="org-empty">Изображение не добавлено</div>'}</div></div>`;
    if(staff&&$('quickEdit'))$('quickEdit').onclick=()=>openEditor(x.id);
    $('orgThumbs').innerHTML=list.map(v=>`<button class="org-thumb ${String(v.id)===String(x.id)?'active':''}" data-id="${esc(v.id)}" title="${esc(v.name)}">${v.image?`<img src="${esc(v.image)}" alt="">`:'<div style="height:115px"></div>'}<small>${esc(v.name)}</small></button>`).join('');
    $('orgThumbs').querySelectorAll('.org-thumb').forEach(b=>b.onclick=()=>{selectedId=b.dataset.id;render()});
  }
  function move(dir){const list=visible();if(!list.length)return;let i=list.findIndex(x=>String(x.id)===String(selectedId));if(i<0)i=0;i=(i+dir+list.length)%list.length;selectedId=list[i].id;render();document.querySelector('.org-thumb.active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}
  function imgToData(file,max=1500){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>5*1024*1024)return reject(new Error('Файл больше 5 МБ'));const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.88))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
  function openEditor(id){if(!staff)return;editingId=id;const x=id?all.find(v=>String(v.id)===String(id)):null;pendingImage=x?.image||'';$('edTitle').textContent=x?'Редактировать организацию':'Добавить организацию';$('edCategory').value=x?D.category(x.category):type;$('edAlign').value=x?D.alignment(x.alignment):align;$('edName').value=x?.name||'';$('edLocation').value=x?.location||'';$('edWeapon').value=x?.weapon||'';$('edContent').value=x?.content||'';$('edJoin').value=x?.howToJoin||'';$('edImage').value='';const p=$('edPreview');if(pendingImage){p.src=pendingImage;p.classList.add('show')}else p.classList.remove('show');$('orgModal').classList.add('open')}
  function closeEditor(){$('orgModal').classList.remove('open');editingId=null;pendingImage=''}
  async function saveEditor(){if(!staff)return;const name=$('edName').value.trim();if(!name)return alert('Укажите название');const old=editingId?all.find(v=>String(v.id)===String(editingId)):null;const item=D.normalize({...old,id:old?.id||('org-'+Date.now()),category:$('edCategory').value,alignment:$('edAlign').value,name,location:$('edLocation').value.trim()||'Не заполнено',weapon:$('edWeapon').value.trim()||'Не заполнено',content:$('edContent').value.trim()||'Описание будет добавлено позже.',howToJoin:$('edJoin').value.trim()||'Информация будет добавлена позже.',image:pendingImage,hidden:false,authorRole:old?.authorRole||JSON.parse(localStorage.getItem('kungfuCurrentUser')||'{}').role||'admin'});if(old){const i=all.indexOf(old);all[i]=item}else all.push(item);D.saveAll(all);type=item.category;align=item.alignment;selectedId=item.id;closeEditor();render()}
  function del(){if(!staff)return;const x=current();if(!x||!confirm(`Удалить «${x.name}»?`))return;const i=all.findIndex(v=>String(v.id)===String(x.id));if(i>=0)all[i]={...all[i],hidden:true};D.saveAll(all);selectedId=null;render()}
  document.querySelectorAll('.org-tab').forEach(b=>b.onclick=()=>{type=b.dataset.type;const entries=all.filter(x=>!x.hidden&&D.category(x.category)===type);const preferred=['Особые','Добро','Нейтральные','Зло'].find(a=>entries.some(x=>D.alignment(x.alignment)===a));align=preferred||'Особые';selectedId=null;render()});
  document.querySelectorAll('.org-align').forEach(b=>b.onclick=()=>{align=b.dataset.align;selectedId=null;render()});
  $('prevOrg').onclick=()=>move(-1);$('nextOrg').onclick=()=>move(1);$('staffAdd').onclick=()=>openEditor(null);$('staffEdit').onclick=()=>{const x=current();if(x)openEditor(x.id)};$('staffDelete').onclick=del;$('edClose').onclick=closeEditor;$('edCancel').onclick=closeEditor;$('edSave').onclick=saveEditor;$('orgModal').onclick=e=>{if(e.target===$('orgModal'))closeEditor()};$('edImage').onchange=async()=>{try{pendingImage=await imgToData($('edImage').files[0]);$('edPreview').src=pendingImage;$('edPreview').classList.add('show')}catch(e){alert(e.message)}};
  const q=new URLSearchParams(location.search);if(q.get('type'))type=D.category(q.get('type'));if(q.get('align'))align=D.alignment(q.get('align'));if(q.get('id'))selectedId=q.get('id');
  role().finally(()=>{render();if(q.get('edit')&&staff)openEditor(q.get('edit'))});
})();
