(()=>{
  const D=window.KFOrganizations;if(!D)return;
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let all=D.loadAll(),id=new URLSearchParams(location.search).get('id'),item=D.findById(id,all),staff=false;
  function cleanRich(html){const t=document.createElement('template');t.innerHTML=html||'';t.content.querySelectorAll('script,iframe,object,embed,style,link').forEach(x=>x.remove());t.content.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(a=>{if(/^on/i.test(a.name))el.removeAttribute(a.name);if((a.name==='href'||a.name==='src')&&/^javascript:/i.test(a.value))el.removeAttribute(a.name)}));return t.innerHTML}
  window.orgCleanRich=cleanRich;
  window.fmt=(cmd,val=null)=>{document.execCommand(cmd,false,val);$('rich')?.focus()};
  window.insertTable=()=>{let rows=parseInt(prompt('Количество строк таблицы','3'),10),cols=parseInt(prompt('Количество колонок','3'),10);if(!Number.isFinite(rows)||!Number.isFinite(cols)||rows<1||cols<1||rows>30||cols>12)return;let html='<table><tbody>';for(let r=0;r<rows;r++){html+='<tr>';for(let c=0;c<cols;c++)html+=`<td>${r===0?'Заголовок':'Текст'}</td>`;html+='</tr>'}html+='</tbody></table><p><br></p>';$('rich').focus();document.execCommand('insertHTML',false,html)};

  function templateHtml(cat){
    const info=D.contentHints(cat),label=D.category(cat),where=label==='Школа'?'школы':label==='Секта'?'секты':'фракции';
    const neigongText=info.neigongs?`<section class="org-reference-section"><h2>Нейгуны</h2><p>Добавьте сюда ${info.neigongs} ${info.neigongs===1?'нейгун':'нейгунов'}: название, описание и изображения. Картинки вставляются кнопкой «Изображение» прямо в текст.</p></section>`:'';
    const reworkText=info.reworks?`<section class="org-reference-section"><h2>Реворки</h2><p>Для школы предусмотрено до ${info.reworks} реворков. Можно оформить каждый реворк отдельным заголовком, текстом и картинкой.</p></section>`:'';
    return `<div class="org-reference-grid"><section class="org-reference-card org-reference-text"><h2>Условия вступления</h2><h3>Общие требования</h3><p>Введите условия вступления.</p><h3>Личные требования</h3><p>Введите дополнительные требования.</p><h3>Боевые требования</h3><p>Введите боевые требования.</p></section><section class="org-reference-card"><h2>Карта ${where}</h2><p>Нажмите сюда и вставьте изображение карты через кнопку «Изображение» в панели редактора.</p></section><section class="org-reference-card"><h2>Титулы ${where}</h2><p>Добавьте изображение титулов и описание.</p></section></div>${neigongText}${reworkText}<section class="org-reference-section"><h2>Предметы</h2><p>Добавьте изображения и описание предметов.</p></section><section class="org-reference-section"><h2>Приёмы и навыки</h2><p>Добавьте изображения и описание приёмов.</p></section><section class="org-reference-section"><h2>Дополнительные материалы</h2><p>Костюмы, специальные скиллы, схемы и любые другие изображения.</p></section>`;
  }

  function render(){
    if(!item||item.hidden){$('detailApp').innerHTML='<div class="detail-empty">Материал не найден.</div>';return}
    document.title=`${item.name} — Легенды Кунг-Фу`;
    const icon=item.thumbImage||item.image||'';
    const article=cleanRich(item.articleHtml||'');
    $('detailApp').innerHTML=`<div class="detail-breadcrumb"><a href="schools.html?type=${encodeURIComponent(item.category)}&align=${encodeURIComponent(item.alignment)}">Школы, секты и фракции</a><span>›</span><span>${esc(item.name)}</span></div>
    <section class="detail-hero org-panel"><div class="detail-copy"><div class="detail-copy-head">${icon?`<div class="org-icon-badge"><img src="${esc(icon)}" alt=""></div>`:''}<div><span class="org-kicker">${esc(item.category)} · ${esc(item.alignment)}</span><h1>${esc(item.name)}</h1></div></div><div class="detail-facts"><div><b>Локация</b><span>${esc(item.location||'Не заполнено')}</span></div><div><b>Оружия</b><span>${esc(item.weapon||'Не заполнено')}</span></div></div><p class="detail-intro">${esc(item.content||'Описание будет добавлено позже.').replace(/\n/g,'<br>')}</p>${staff?'<div class="org-actions"><button class="org-btn primary" id="detailEdit">Редактировать контент</button><a class="org-btn" href="schools.html?id='+encodeURIComponent(item.id)+'&type='+encodeURIComponent(item.category)+'&align='+encodeURIComponent(item.alignment)+'">Карточка организации</a></div>':''}</div><div class="detail-image">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.name)}">`:''}</div></section>
    ${article?`<section class="org-panel org-article-panel"><div class="rich-output org-article">${article}</div></section>`:`<section class="org-panel org-article-panel"><div class="detail-empty">Контент пока не добавлен.${staff?' Нажмите «Редактировать контент», чтобы создать материал.':''}</div></section>`}
    <div class="detail-bottom"><a class="org-btn" href="schools.html?type=${encodeURIComponent(item.category)}&align=${encodeURIComponent(item.alignment)}">← Вернуться к витрине</a></div>`;
    if(staff&&$('detailEdit'))$('detailEdit').onclick=openEditor;
  }
  async function role(){let u=null;try{u=JSON.parse(localStorage.getItem('kungfuCurrentUser')||'null')}catch{};staff=!!u&&['admin','moderator'].includes(u.role||'user');if(window.KFSupabase?.ready){try{await window.KFSupabase.ready;const p=await window.KFSupabase.getCurrentProfile();if(p)staff=['admin','moderator'].includes(p.role||'user')}catch{}}}
  function openEditor(){if(!staff||!item)return;$('rich').innerHTML=item.articleHtml||'';$('dSaveStatus').textContent='';$('detailModal').classList.add('open');setTimeout(()=>window.KFImageTools?.bindEditors?.(),0)}
  function closeEditor(){$('detailModal').classList.remove('open');$('dSaveStatus').textContent=''}
  async function save(){if(!staff||!item)return;const html=cleanRich($('rich').innerHTML);const i=all.findIndex(x=>String(x.id)===String(item.id));if(i<0)return;$('dSave').disabled=true;$('dSaveStatus').textContent='Сохраняю текст и изображения…';all[i]=D.normalize({...item,articleHtml:html,authorRole:item.authorRole||JSON.parse(localStorage.getItem('kungfuCurrentUser')||'{}').role||'admin'});try{all=await D.persist(all);item=D.findById(id,all);$('dSaveStatus').textContent='Сохранено.';setTimeout(()=>{closeEditor();render()},350)}catch(e){$('dSaveStatus').textContent='Ошибка сохранения.';alert(e.message||'Не удалось сохранить контент')}finally{$('dSave').disabled=false}}
  $('dClose').onclick=closeEditor;$('dCancel').onclick=closeEditor;$('dSave').onclick=save;$('detailModal').onclick=e=>{if(e.target===$('detailModal'))closeEditor()};$('dTemplate').onclick=()=>{if($('rich').innerText.trim()&&!confirm('Заменить текущий контент шаблоном?'))return;$('rich').innerHTML=templateHtml(item?.category||'Школа');window.KFImageTools?.bindEditors?.()};
  Promise.all([role(),D.hydrate().then(v=>{all=v;item=D.findById(id,all)})]).finally(()=>{render();if(new URLSearchParams(location.search).get('edit')&&staff)setTimeout(openEditor,50)});
})();
