(()=>{
  const D=window.KFOrganizations;if(!D)return;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let all=D.loadAll(), id=new URLSearchParams(location.search).get('id'), item=D.findById(id,all), staff=false;
  let pendingImage='', pendingThumb='', pendingNeigongs=[], pendingReworks=[], pendingMedia=[];
  const clone=v=>JSON.parse(JSON.stringify(v||[]));
  function lines(v){return String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}
  function safe(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
  function currentCategory(){return D.category($('dCategory')?.value || item?.category || 'Школа')}
  function limitConfig(){return D.getLimits(currentCategory())}
  function imgToData(file,max=1600){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>5*1024*1024)return reject(new Error('Файл больше 5 МБ'));const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.88))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
  function renderPreview(imgId,value){const el=$(imgId);if(!el)return;if(value){el.src=value;el.classList.add('show')}else{el.removeAttribute('src');el.classList.remove('show')}}

  function cards(title,arr){if(!Array.isArray(arr)||!arr.length)return'';return `<section class="detail-section org-panel"><h2>${esc(title)}</h2><div class="detail-cards">${arr.map(x=>`<article>${x.image?`<img src="${esc(x.image)}" alt="">`:''}<div><h3>${esc(x.name||x.title||'')}</h3><p>${esc(x.description||x.caption||'').replace(/\n/g,'<br>')}</p></div></article>`).join('')}</div></section>`}
  function mediaSection(arr){if(!Array.isArray(arr)||!arr.length)return'';return `<section class="detail-section org-panel"><h2>Материалы</h2><div class="detail-media-grid">${arr.map(x=>`<figure>${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title||x.name||'')}">`:''}${x.title?`<h3>${esc(x.title)}</h3>`:''}${x.caption?`<figcaption>${esc(x.caption).replace(/\n/g,'<br>')}</figcaption>`:''}</figure>`).join('')}</div></section>`}
  function renderLinks(v){const a=lines(v);if(!a.length)return'';return `<section class="detail-section org-panel"><h2>Ссылки</h2><ul class="detail-links detail-bullets">${a.map(s=>{const p=s.split('|'),url=safe((p[1]||p[0]).trim()),label=(p[1]?p[0]:'Перейти').trim();return url?`<li><a href="${url}" target="_blank" rel="noopener">${esc(label)}</a></li>`:`<li>${esc(s)}</li>`}).join('')}</ul></section>`}

  function render(){
    if(!item||item.hidden){$('detailApp').innerHTML='<div class="detail-empty">Материал не найден.</div>';return}
    document.title=`${item.name} — Легенды Кунг-Фу`;
    const icon=item.thumbImage||item.image||'';
    $('detailApp').innerHTML=`<div class="detail-breadcrumb"><a href="schools.html?type=${encodeURIComponent(item.category)}&align=${encodeURIComponent(item.alignment)}">Школы, секты и фракции</a><span>›</span><span>${esc(item.name)}</span></div>
    <section class="detail-hero org-panel"><div class="detail-copy"><div class="detail-copy-head">${icon?`<div class="org-icon-badge"><img src="${esc(icon)}" alt="${esc(item.name)}"></div>`:''}<div><span class="org-kicker">${esc(item.category)} · ${esc(item.alignment)}</span><h1>${esc(item.name)}</h1></div></div><div class="detail-facts"><div><b>Локация</b><span>${esc(item.location||'Не заполнено')}</span></div><div><b>Оружия</b><span>${esc(item.weapon||'Не заполнено')}</span></div></div><p class="detail-intro">${esc(item.content||'Описание будет добавлено позже.').replace(/\n/g,'<br>')}</p>${staff?'<div style="margin-top:18px"><button class="org-btn primary" id="detailEdit">Редактировать страницу</button></div>':''}</div><div class="detail-image">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.name)}">`:''}</div></section>
    <section class="detail-section org-panel"><h2>Как вступить?</h2><p>${esc(item.howToJoin||'Информация будет добавлена позже.').replace(/\n/g,'<br>')}</p></section>
    ${cards('Нейгуны',item.neigongCards)}${cards('Реворки',item.reworkCards)}${cards('Навыки',item.skillCards)}${mediaSection(item.mediaCards)}${renderLinks(item.links)}<div class="detail-bottom"><a class="org-btn" href="schools.html?type=${encodeURIComponent(item.category)}&align=${encodeURIComponent(item.alignment)}">← Вернуться к витрине</a></div>`;
    if(staff&&$('detailEdit'))$('detailEdit').onclick=openEditor;
  }
  async function role(){let u=null;try{u=JSON.parse(localStorage.getItem('kungfuCurrentUser')||'null')}catch{};staff=!!u&&['admin','moderator'].includes(u.role||'user');if(window.KFSupabase?.ready){try{await window.KFSupabase.ready;const p=await window.KFSupabase.getCurrentProfile();if(p)staff=['admin','moderator'].includes(p.role||'user')}catch{}}}

  function updateLimitBlocks(){const limits=limitConfig();$('dNeigongLimit').textContent=`Лимит: ${limits.neigongs}`;$('dReworkLimit').textContent=limits.reworks?`Лимит: ${limits.reworks}`:'Для этого типа организации реворки не предусмотрены';const reworkSection=$('dReworks').closest('.org-repeat-section');reworkSection.style.display=limits.reworks?'block':'none';$('dAddRework').style.display=limits.reworks?'inline-flex':'none'}
  function itemRow(kind,item,index){const labelMap={neigongs:'Нейгун',reworks:'Реворк',media:'Изображение'};const titleLabel=kind==='media'?'Заголовок':'Название';const descLabel=kind==='media'?'Подпись / текст':'Описание';const title=item.title||item.name||'';const desc=kind==='media'?(item.caption||item.description||''):(item.description||item.caption||'');return `<div class="org-repeat-item"><div class="org-repeat-top"><div class="org-repeat-title">${labelMap[kind]} ${index+1}</div><button class="org-btn danger" type="button" data-kind="${kind}" data-action="remove" data-index="${index}">Удалить</button></div><div class="org-repeat-grid"><div class="preview-wrap">${item.image?`<img src="${esc(item.image)}" alt="">`:`<div class="preview-empty">Изображение не добавлено</div>`}<div class="org-helper">PNG, JPG, WEBP — до 5 МБ</div><input type="file" accept="image/*" data-kind="${kind}" data-action="image" data-index="${index}" style="margin-top:10px;width:100%"></div><div class="org-repeat-fields"><div><input data-kind="${kind}" data-field="title" data-index="${index}" value="${esc(title)}" placeholder="${titleLabel}"></div><div><textarea data-kind="${kind}" data-field="description" data-index="${index}" placeholder="${descLabel}">${esc(desc)}</textarea></div></div></div></div>`}
  function renderRepeater(kind){const map={neigongs:pendingNeigongs,reworks:pendingReworks,media:pendingMedia};const targetId={neigongs:'dNeigongs',reworks:'dReworks',media:'dMedia'}[kind];const arr=map[kind];const target=$(targetId);target.innerHTML=`<div class="org-repeat-list">${arr.length?arr.map((item,index)=>itemRow(kind,item,index)).join(''):`<div class="org-helper">${kind==='media'?'Здесь можно хранить картинки фракции, предметов, костюмов, карт и любые визуальные материалы.':'Пока ничего не добавлено.'}</div>`}</div>`;target.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const idx=Number(el.dataset.index);const field=el.dataset.field;const list=map[el.dataset.kind];if(!list[idx])return;if(kind==='media'){if(field==='title')list[idx].title=el.value;else list[idx].caption=el.value}else{if(field==='title')list[idx].name=el.value;else list[idx].description=el.value}});target.querySelectorAll('[data-action="remove"]').forEach(btn=>btn.onclick=()=>{const list=map[btn.dataset.kind];list.splice(Number(btn.dataset.index),1);renderRepeater(btn.dataset.kind)});target.querySelectorAll('[data-action="image"]').forEach(input=>input.onchange=async()=>{try{const idx=Number(input.dataset.index);const list=map[input.dataset.kind];if(!list[idx])return;list[idx].image=await imgToData(input.files[0]);renderRepeater(input.dataset.kind)}catch(e){alert(e.message)}})}
  function addRepeater(kind){const limits=limitConfig();const map={neigongs:pendingNeigongs,reworks:pendingReworks,media:pendingMedia};const limit=kind==='neigongs'?limits.neigongs:(kind==='reworks'?limits.reworks:Infinity);if(map[kind].length>=limit){alert(`Достигнут лимит для раздела: ${limit}`);return}map[kind].push(kind==='media'?{title:'',caption:'',image:''}:{name:'',description:'',image:''});renderRepeater(kind)}

  function openEditor(){if(!staff||!item)return;pendingImage=item.image||'';pendingThumb=item.thumbImage||item.image||'';pendingNeigongs=clone(item.neigongCards||[]);pendingReworks=clone(item.reworkCards||[]);pendingMedia=clone(item.mediaCards||[]);$('dCategory').value=item.category;$('dAlign').value=item.alignment;$('dName').value=item.name;$('dLocation').value=item.location||'';$('dWeapon').value=item.weapon||'';$('dContent').value=item.content||'';$('dJoin').value=item.howToJoin||'';$('dImage').value='';$('dThumb').value='';renderPreview('dPreview',pendingImage);renderPreview('dThumbPreview',pendingThumb);updateLimitBlocks();renderRepeater('neigongs');renderRepeater('reworks');renderRepeater('media');$('detailModal').classList.add('open')}
  function closeEditor(){$('detailModal').classList.remove('open')}
  function save(){if(!staff)return;const name=$('dName').value.trim();if(!name)return alert('Укажите название');const updated=D.normalize({...item,category:$('dCategory').value,alignment:$('dAlign').value,name,location:$('dLocation').value.trim()||'Не заполнено',weapon:$('dWeapon').value.trim()||'Не заполнено',content:$('dContent').value.trim()||'Описание будет добавлено позже.',howToJoin:$('dJoin').value.trim()||'Информация будет добавлена позже.',image:pendingImage,thumbImage:pendingThumb,neigongCards:pendingNeigongs,reworkCards:pendingReworks,mediaCards:pendingMedia});const i=all.findIndex(x=>String(x.id)===String(item.id));all[i]=updated;item=updated;D.saveAll(all);all=D.loadAll();closeEditor();render()}

  $('dClose').onclick=closeEditor; $('dCancel').onclick=closeEditor; $('dSave').onclick=save; $('detailModal').onclick=e=>{if(e.target===$('detailModal'))closeEditor()};
  $('dImage').onchange=async()=>{try{pendingImage=await imgToData($('dImage').files[0]);renderPreview('dPreview',pendingImage)}catch(e){alert(e.message)}};
  $('dThumb').onchange=async()=>{try{pendingThumb=await imgToData($('dThumb').files[0],900);renderPreview('dThumbPreview',pendingThumb)}catch(e){alert(e.message)}};
  $('dCategory').onchange=()=>{updateLimitBlocks();renderRepeater('neigongs');renderRepeater('reworks')};
  $('dAddNeigong').onclick=()=>addRepeater('neigongs'); $('dAddRework').onclick=()=>addRepeater('reworks'); $('dAddMedia').onclick=()=>addRepeater('media');
  role().finally(()=>{all=D.loadAll();item=D.findById(id,all);render()});
})();
