-- Легенды Кунг-Фу 0.0.55 — отзывы к партнерам

create table if not exists public.partner_reviews (
  id bigint generated by default as identity primary key,
  partner_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 1500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_partner_reviews_partner_created
on public.partner_reviews(partner_id, created_at);

alter table public.partner_reviews enable row level security;

drop policy if exists "partner_reviews_public_read" on public.partner_reviews;
create policy "partner_reviews_public_read"
on public.partner_reviews for select
to anon, authenticated
using (true);

drop policy if exists "partner_reviews_insert_own" on public.partner_reviews;
create policy "partner_reviews_insert_own"
on public.partner_reviews for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "partner_reviews_update_own_or_admin" on public.partner_reviews;
create policy "partner_reviews_update_own_or_admin"
on public.partner_reviews for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "partner_reviews_delete_own_or_admin" on public.partner_reviews;
create policy "partner_reviews_delete_own_or_admin"
on public.partner_reviews for delete
to authenticated
using (user_id = auth.uid() or public.is_admin());

grant select on public.partner_reviews to anon, authenticated;
grant insert, update, delete on public.partner_reviews to authenticated;
grant usage, select on sequence public.partner_reviews_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'partner_reviews'
  ) then
    alter publication supabase_realtime add table public.partner_reviews;
  end if;
end $$;
